<%@page import="com.purplehillsbooks.weaver.DOMFace"
%><%@page import="com.purplehillsbooks.weaver.AddressListEntry"
%><%@page import="com.purplehillsbooks.weaver.AttachmentRecord"
%><%@page import="com.purplehillsbooks.weaver.AuthRequest"
%><%@page import="com.purplehillsbooks.weaver.HistoryRecord"
%><%@page import="com.purplehillsbooks.weaver.TopicRecord"
%><%@page import="com.purplehillsbooks.weaver.LeafletResponseRecord"
%><%@page import="com.purplehillsbooks.weaver.License"
%><%@page import="com.purplehillsbooks.weaver.LicensedURL"
%><%@page import="com.purplehillsbooks.weaver.NGBook"
%><%@page import="com.purplehillsbooks.weaver.NGContainer"
%><%@page import="com.purplehillsbooks.weaver.NGPage"
%><%@page import="com.purplehillsbooks.weaver.NGPageIndex"
%><%@page import="com.purplehillsbooks.weaver.NGRole"
%><%@page import="com.purplehillsbooks.weaver.NGSection"
%><%@page import="com.purplehillsbooks.weaver.NGSession"
%><%@page import="com.purplehillsbooks.weaver.ProcessRecord"
%><%@page import="com.purplehillsbooks.weaver.SectionAttachments"
%><%@page import="com.purplehillsbooks.weaver.SectionForNotes"
%><%@page import="com.purplehillsbooks.weaver.SectionDef"
%><%@page import="com.purplehillsbooks.weaver.SectionFormat"
%><%@page import="com.purplehillsbooks.weaver.SectionTask"
%><%@page import="com.purplehillsbooks.weaver.SectionUtil"
%><%@page import="com.purplehillsbooks.weaver.GoalRecord"
%><%@page import="com.purplehillsbooks.weaver.UserManager"
%><%@page import="com.purplehillsbooks.weaver.UserPage"
%><%@page import="com.purplehillsbooks.weaver.UserProfile"
%><%@page import="com.purplehillsbooks.weaver.UserRef"
%><%@page import="com.purplehillsbooks.weaver.UtilityMethods"
%><%@page import="com.purplehillsbooks.weaver.WikiConverter"
%><%@page import="com.purplehillsbooks.weaver.mail.EmailSender"
%><%@page import="java.io.File"
%><%@page import="java.io.Writer"
%><%@page import="java.io.Writer"
%><%@page import="java.net.URLEncoder"
%><%@page import="java.text.SimpleDateFormat"
%><%@page import="java.util.ArrayList"
%><%@page import="java.util.Date"
%><%@page import="java.util.Enumeration"
%><%@page import="java.util.List"
%><%@page import="java.util.Properties"
%><%@page import="java.util.StringTokenizer"
%><%@page import="java.util.Vector"
%><%!

    private NGWorkspace ngp = null;
    private NGBook ngb = null;
    boolean needTomcatKludge = false;


%>
